import { defineConfig } from "vitest/config";
import path from "node:path";

const alias = (name: string) => path.resolve(__dirname, `packages/${name}/src/index.ts`);

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts", "packages/**/*.test.ts"],
  },
  resolve: {
    alias: {
      "@aether/types": alias("aether-types"),
      "@aether/kernel": alias("aether-kernel"),
      "@aether/audit": alias("aether-audit"),
      "@aether/policy": alias("aether-policy"),
      "@aether/ledger": alias("aether-ledger"),
      "@aether/identity": alias("aether-identity"),
      "@aether/mandate": alias("aether-mandate"),
      "@aether/envelope": alias("aether-envelope"),
      "@aether/escrow": alias("aether-escrow"),
      "@aether/market": alias("aether-market"),
      "@aether/settlement": alias("aether-settlement"),
      "@aether/clearing": alias("aether-clearing"),
      "@aether/kya": alias("aether-kya"),
      "@aether/runtime": alias("aether-runtime"),
      "@aether/sprint": path.resolve(__dirname, "packages/aether-runtime/src/sprint-procurement.ts"),
      "@aether/night-watch": path.resolve(__dirname, "packages/aether-runtime/src/night-watch.ts"),
      "@aether/sub-hire": path.resolve(__dirname, "packages/aether-runtime/src/sub-hire.ts"),
      "@aether/clearing-window": path.resolve(__dirname, "packages/aether-runtime/src/clearing-window.ts"),
      "@aether/refund": path.resolve(__dirname, "packages/aether-runtime/src/refund.ts"),
      "@aether/replay": path.resolve(__dirname, "packages/aether-runtime/src/replay.ts"),
      "@aether/envelope-nonce": path.resolve(__dirname, "packages/aether-runtime/src/envelope-nonce.ts"),
      "@aether/deny-cache": path.resolve(__dirname, "packages/aether-runtime/src/deny-cache.ts"),
      "@aether/recurrence-cadence": path.resolve(__dirname, "packages/aether-runtime/src/recurrence-cadence.ts"),
      "@aether/execution-window": path.resolve(__dirname, "packages/aether-runtime/src/execution-window.ts"),
      "@aether/cadence-slot": path.resolve(__dirname, "packages/aether-runtime/src/cadence-slot.ts"),
      "@aether/daily-gap": path.resolve(__dirname, "packages/aether-runtime/src/daily-gap.ts"),
      "@aether/cart-occupancy": path.resolve(__dirname, "packages/aether-runtime/src/cart-occupancy.ts"),
      "@aether/hot-hour": path.resolve(__dirname, "packages/aether-runtime/src/hot-hour.ts"),
      "@aether/operator-door": path.resolve(__dirname, "packages/aether-runtime/src/operator-door.ts"),
      "@aether/cart-match": path.resolve(__dirname, "packages/aether-runtime/src/cart-match.ts"),
      "@aether/closed-room": path.resolve(__dirname, "packages/aether-runtime/src/closed-room.ts"),
      "@aether/fx-not-hire": path.resolve(__dirname, "packages/aether-runtime/src/fx-not-hire.ts"),
      "@aether/unique-live": path.resolve(__dirname, "packages/aether-runtime/src/unique-live.ts"),
      "@aether/spread-bound": path.resolve(__dirname, "packages/aether-runtime/src/spread-bound.ts"),
      "@aether/parent-fresh": path.resolve(__dirname, "packages/aether-runtime/src/parent-fresh.ts"),
      "@aether/mandate-parent": path.resolve(__dirname, "packages/aether-runtime/src/mandate-parent.ts"),
      "@aether/mm-inventory": path.resolve(__dirname, "packages/aether-runtime/src/mm-inventory.ts"),
      "@aether/payment-budget": path.resolve(__dirname, "packages/aether-runtime/src/payment-budget.ts"),
      "@aether/host-unique": path.resolve(__dirname, "packages/aether-runtime/src/host-unique.ts"),
      "@aether/payment-parent": path.resolve(__dirname, "packages/aether-runtime/src/payment-parent.ts"),
      "@aether/operating-book": path.resolve(__dirname, "packages/aether-runtime/src/operating-book.ts"),
      "@aether/payment-payees": path.resolve(__dirname, "packages/aether-runtime/src/payment-payees.ts"),
      "@aether/capability-subset": path.resolve(__dirname, "packages/aether-runtime/src/capability-subset.ts"),
      "@aether/fx-fresh": path.resolve(__dirname, "packages/aether-runtime/src/fx-fresh.ts"),
      "@aether/window-reach": path.resolve(__dirname, "packages/aether-runtime/src/window-reach.ts"),
      "@aether/kya-window": path.resolve(__dirname, "packages/aether-runtime/src/kya-window.ts"),
      "@aether/circuit-daily": path.resolve(__dirname, "packages/aether-runtime/src/circuit-daily.ts"),
      "@aether/payment-skus": path.resolve(__dirname, "packages/aether-runtime/src/payment-skus.ts"),
      "@aether/sku-currency": path.resolve(__dirname, "packages/aether-runtime/src/sku-currency.ts"),
      "@aether/hire-party": path.resolve(__dirname, "packages/aether-runtime/src/hire-party.ts"),
      "@aether/ledger-sufficient": path.resolve(__dirname, "packages/aether-runtime/src/ledger-sufficient.ts"),
      "@aether/not-expired": path.resolve(__dirname, "packages/aether-runtime/src/not-expired.ts"),
      "@aether/chain-integrity": path.resolve(__dirname, "packages/aether-runtime/src/chain-integrity.ts"),
      "@aether/hire-state": path.resolve(__dirname, "packages/aether-runtime/src/hire-state.ts"),
      "@aether/ledger-known": path.resolve(__dirname, "packages/aether-runtime/src/ledger-known.ts"),
      "@aether/kya-party": path.resolve(__dirname, "packages/aether-runtime/src/kya-party.ts"),
      "@aether/fx-window": path.resolve(__dirname, "packages/aether-runtime/src/fx-window.ts"),
      "@aether/intent-subject": path.resolve(__dirname, "packages/aether-runtime/src/intent-subject.ts"),
      "@aether/fx-quote": path.resolve(__dirname, "packages/aether-runtime/src/fx-quote.ts"),
      "@aether/same-currency": path.resolve(__dirname, "packages/aether-runtime/src/same-currency.ts"),
      "@aether/ladder-legal": path.resolve(__dirname, "packages/aether-runtime/src/ladder-legal.ts"),
      "@aether/min-level": path.resolve(__dirname, "packages/aether-runtime/src/min-level.ts"),
      "@aether/birth-rung": path.resolve(__dirname, "packages/aether-runtime/src/birth-rung.ts"),
      "@aether/max-autonomy": path.resolve(__dirname, "packages/aether-runtime/src/max-autonomy.ts"),
      "@aether/attestation-fresh": path.resolve(__dirname, "packages/aether-runtime/src/attestation-fresh.ts"),
      "@aether/approval-pending": path.resolve(__dirname, "packages/aether-runtime/src/approval-pending.ts"),
      "@aether/kya-not-self": path.resolve(__dirname, "packages/aether-runtime/src/kya-not-self.ts"),
      "@aether/host-authority": path.resolve(__dirname, "packages/aether-runtime/src/host-authority.ts"),
      "@aether/occurrence-fresh": path.resolve(__dirname, "packages/aether-runtime/src/occurrence-fresh.ts"),
      "@aether/role-capability": path.resolve(__dirname, "packages/aether-runtime/src/role-capability.ts"),
      "@aether/amount-range": path.resolve(__dirname, "packages/aether-runtime/src/amount-range.ts"),
      "@aether/escrow-required": path.resolve(__dirname, "packages/aether-runtime/src/escrow-required.ts"),
      "@aether/known-sku": path.resolve(__dirname, "packages/aether-runtime/src/known-sku.ts"),
      "@aether/known-rfq": path.resolve(__dirname, "packages/aether-runtime/src/known-rfq.ts"),
      "@aether/known-intent": path.resolve(__dirname, "packages/aether-runtime/src/known-intent.ts"),
      "@aether/known-cart": path.resolve(__dirname, "packages/aether-runtime/src/known-cart.ts"),
      "@aether/known-hire": path.resolve(__dirname, "packages/aether-runtime/src/known-hire.ts"),
      "@aether/known-parent": path.resolve(__dirname, "packages/aether-runtime/src/known-parent.ts"),
      "@aether/known-approval": path.resolve(__dirname, "packages/aether-runtime/src/known-approval.ts"),
      "@aether/kya-known-parent": path.resolve(__dirname, "packages/aether-runtime/src/kya-known-parent.ts"),
      "@aether/known-attestation": path.resolve(__dirname, "packages/aether-runtime/src/known-attestation.ts"),
      "@aether/known-invitee": path.resolve(__dirname, "packages/aether-runtime/src/known-invitee.ts"),
      "@aether/cart-fresh": path.resolve(__dirname, "packages/aether-runtime/src/cart-fresh.ts"),
      "@aether/freeze-state": path.resolve(__dirname, "packages/aether-runtime/src/freeze-state.ts"),
      "@aether/unique-key": path.resolve(__dirname, "packages/aether-runtime/src/unique-key.ts"),
      "@aether/system-scope": path.resolve(__dirname, "packages/aether-runtime/src/system-scope.ts"),
      "@aether/actor-known": path.resolve(__dirname, "packages/aether-runtime/src/actor-known.ts"),
      "@aether/receipt-known": path.resolve(__dirname, "packages/aether-runtime/src/receipt-known.ts"),
      "@aether/kya-mint-fresh": path.resolve(__dirname, "packages/aether-runtime/src/kya-mint-fresh.ts"),
      "@aether/window-fresh": path.resolve(__dirname, "packages/aether-runtime/src/window-fresh.ts"),
      "@aether/mm-known": path.resolve(__dirname, "packages/aether-runtime/src/mm-known.ts"),
      "@aether/currency-match": path.resolve(__dirname, "packages/aether-runtime/src/currency-match.ts"),
      "@aether/safe-balance": path.resolve(__dirname, "packages/aether-runtime/src/safe-balance.ts"),
      "@aether/fx-pair": path.resolve(__dirname, "packages/aether-runtime/src/fx-pair.ts"),
      "@aether/approval-replay": path.resolve(__dirname, "packages/aether-runtime/src/approval-replay.ts"),
      "@aether/chain-intact": path.resolve(__dirname, "packages/aether-runtime/src/chain-intact.ts"),
      "@aether/principal-not-frozen": path.resolve(__dirname, "packages/aether-runtime/src/principal-not-frozen.ts"),
      "@aether/allowed-instruments": path.resolve(__dirname, "packages/aether-runtime/src/allowed-instruments.ts"),
      "@aether/human-signature": path.resolve(__dirname, "packages/aether-runtime/src/human-signature.ts"),
      "@aether/delegation-depth": path.resolve(__dirname, "packages/aether-runtime/src/delegation-depth.ts"),
      "@aether/payment-reference": path.resolve(__dirname, "packages/aether-runtime/src/payment-reference.ts"),
      "@aether/identity-party": path.resolve(__dirname, "packages/aether-runtime/src/identity-party.ts"),
      "@aether/hire-void": path.resolve(__dirname, "packages/aether-runtime/src/hire-void.ts"),
      "@aether/market-party": path.resolve(__dirname, "packages/aether-runtime/src/market-party.ts"),
      "@aether/mandate-party": path.resolve(__dirname, "packages/aether-runtime/src/mandate-party.ts"),
      "@aether/rfq-party": path.resolve(__dirname, "packages/aether-runtime/src/rfq-party.ts"),
      "@aether/cart-party": path.resolve(__dirname, "packages/aether-runtime/src/cart-party.ts"),
      "@aether/payment-party": path.resolve(__dirname, "packages/aether-runtime/src/payment-party.ts"),
      "@aether/cadence-reach": path.resolve(__dirname, "packages/aether-runtime/src/cadence-reach.ts"),
      "@aether/range-fresh": path.resolve(__dirname, "packages/aether-runtime/src/range-fresh.ts"),
      "@aether/budget-fresh": path.resolve(__dirname, "packages/aether-runtime/src/budget-fresh.ts"),
      "@aether/currency-fresh": path.resolve(__dirname, "packages/aether-runtime/src/currency-fresh.ts"),
      "@aether/hatch-fresh": path.resolve(__dirname, "packages/aether-runtime/src/hatch-fresh.ts"),
      "@aether/cap-fresh": path.resolve(__dirname, "packages/aether-runtime/src/cap-fresh.ts"),
      "@aether/grant-fresh": path.resolve(__dirname, "packages/aether-runtime/src/grant-fresh.ts"),
      "@aether/nest-tighter": path.resolve(__dirname, "packages/aether-runtime/src/nest-tighter.ts"),
      "@aether/path-tighter": path.resolve(__dirname, "packages/aether-runtime/src/path-tighter.ts"),
      "@aether/path-live": path.resolve(__dirname, "packages/aether-runtime/src/path-live.ts"),
      "@aether/child-currency": path.resolve(__dirname, "packages/aether-runtime/src/child-currency.ts"),
      "@aether/payout-fresh": path.resolve(__dirname, "packages/aether-runtime/src/payout-fresh.ts"),
      "@aether/fx-maker": path.resolve(__dirname, "packages/aether-runtime/src/fx-maker.ts"),
      "@aether/rate-fresh": path.resolve(__dirname, "packages/aether-runtime/src/rate-fresh.ts"),
      "@aether/nest-party": path.resolve(__dirname, "packages/aether-runtime/src/nest-party.ts"),
      "@aether/checkout-party": path.resolve(__dirname, "packages/aether-runtime/src/checkout-party.ts"),
      "@aether/hire-room-party": path.resolve(__dirname, "packages/aether-runtime/src/hire-room-party.ts"),
      "@aether/hire-slip-party": path.resolve(__dirname, "packages/aether-runtime/src/hire-slip-party.ts"),
      "@aether/child-party": path.resolve(__dirname, "packages/aether-runtime/src/child-party.ts"),
      "@aether/root-party": path.resolve(__dirname, "packages/aether-runtime/src/root-party.ts"),
    },
  },
});
